# Project information

site_name: Identity Round Robin
#site_short_name: Identity Round Robin
site_description: 'A hands-on workshop to learn about a variety of AWS identity topics.'
site_author: 'jnv@amazon.com'
#site_url: 'https://jeremyvincent.com/aws-identity-round-robin-workshop'
site_url: 'https://jnv-aws-test-website/aws-identity-round-robin-workshop/'

# Repository
repo_name: 'jvincentnz/aws-identity-round-robin-workshop'
repo_url: 'https://github.com/jvincentnz/aws-identity-round-robin-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences


# Navigation
nav:
  - Overview: 'index.md'
  - 'Serverless Identity':
    - 'Scenario': 'serverless/index.md'
    - 'Task 1': 'serverless/task1.md'
    - 'Task 2': 'serverless/task2.md'
  - 'Access Delegation':
    - 'Scenario': 'delegation/index.md'
    - 'Build Phase': 'delegation/build.md'
    - 'Verify Phase': 'delegation/verify.md'
  - 'Permissions Boundaries - Basic':
    - 'Scenario': 'permission-boundaries/index.md'
    - 'Build Phase': 'permission-boundaries/build.md'
    - 'Verify Phase': 'permission-boundaries/verify.md'
    - 'Cleanup Phase': 'permission-boundaries/cleanup.md'
  - 'Permissions Boundaries - Advanced':
    - 'Scenario': 'permission-boundaries-advanced/index.md'
    - 'Build Phase': 'permission-boundaries-advanced/build.md'
    - 'Verify Phase': 'permission-boundaries-advanced/verify.md'

  - Contributing: 'contribute.md'
  - License: 'license.md'